### ISSUE TITLE
Updating Information on SWARM

### ISSUE THREAD

**Issue by redteamhacker** [avgjoesecurity/CisternAttack#2]
Hello,

I would like to have my name listed correctly in the comments on this page. You have it spelled incorrectly. Tim Wright is the proper spelling. 

Also It would be nice to have our work cited as the first published work and not as a footnote. I do understand that you are frustrated that your talk was not picked. But this does not lessen our work nor should it sound (as it does currently on the page). SWARM was the first published research on this topic and we publicly presented on this at Debycon 9 in 2019. Joe was at this talk, and while he did speak to us about his research the data we saw at that time was not this indepth nor was the code this complete. We were informed that the code was still in flight at the time of our talk. 

I do support and encourage further research in any area but since myself and Jacob were the first to publish on this topic and publicly speak we should be given more credit in the notes on this GIT. To state that your work was done but not accepted does sound a bit belittling to our research and time spent developing code in this area. 

Again, all we are asking for is proper recognition that while multiple teams were working on this attack path, our work was selected to present first. Thus, that make this finding ours and we are just asking for credit in the work. 

This should be noted at the top of the ISSUES file to be fair to our work. It should also be noted in the README file for proper citation of work. 

Thank you,

Timothy Wright

**Comment by bbriggs** [comment]
you are welcome to open a pull request
